export const dummyProperties = [
  {
    id: "1",
    title: "Modern Luxury Apartment",
    description:
      "A stunning luxury apartment with modern interiors, spacious rooms, and premium city views.",
    propertyType: "apartment",
    listingType: "rent",
    location: "Manhattan, New York",
    address: "Manhattan, New York",
    price: 2500,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 1,
    area: 2200,
    featured: true,
    image: "/images/image1.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    ownerId: "dummy-owner",
  },

  {
    id: "2",
    title: "Contemporary Family Villa",
    description:
      "Beautiful contemporary villa featuring elegant architecture, large living spaces, and a private outdoor area.",
    propertyType: "villa",
    listingType: "sale",
    location: "Beverly Hills, Los Angeles",
    address: "Beverly Hills, Los Angeles",
    price: 850000,
    bedrooms: 5,
    bathrooms: 4,
    parkingSpaces: 2,
    area: 4500,
    featured: true,
    image: "/images/image2.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    ownerId: "dummy-owner",
  },

  {
    id: "3",
    title: "Minimalist Smart Home",
    description:
      "Fully automated smart home with premium finishes, floor-to-ceiling windows, and advanced home technology.",
    propertyType: "smart home",
    listingType: "rent",
    location: "Tokyo, Japan",
    address: "Tokyo, Japan",
    price: 4200,
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 1,
    area: 2800,
    featured: false,
    image: "/images/image3.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    ownerId: "dummy-owner",
  },

  {
    id: "4",
    title: "Elegant Waterfront Duplex",
    description:
      "Luxury waterfront duplex with private parking, rooftop terrace, and direct marina views.",
    propertyType: "duplex",
    listingType: "sale",
    location: "Dubai Marina, Dubai",
    address: "Dubai Marina, Dubai",
    price: 1250000,
    bedrooms: 6,
    bathrooms: 5,
    parkingSpaces: 2,
    area: 5200,
    featured: true,
    image: "/images/image4.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    ownerId: "dummy-owner",
  },

  {
    id: "5",
    title: "Urban Studio Apartment",
    description:
      "Compact and stylish studio apartment perfect for young professionals.",
    propertyType: "studio",
    listingType: "rent",
    location: "Paris, France",
    address: "Paris, France",
    price: 1200,
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 0,
    area: 850,
    featured: false,
    image: "/images/image5.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    ownerId: "dummy-owner",
  },

  {
    id: "6",
    title: "Premium Penthouse Suite",
    description:
      "Exclusive penthouse suite with panoramic ocean views, luxury amenities, and refined interiors.",
    propertyType: "penthouse",
    listingType: "sale",
    location: "London, United Kingdom",
    address: "London, United Kingdom",
    price: 2500000,
    bedrooms: 5,
    bathrooms: 6,
    parkingSpaces: 3,
    area: 6800,
    featured: true,
    image: "/images/image6.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    ownerId: "dummy-owner",
  },
];
